groups:
- name: flask-app-alerts
  rules:
  - alert: TooManyRequestCounts
    expr: sum(flask_request_count_total) by (job,endpoint) > 20
    for: 5s
    labels:
      severity: critical
    annotations:
      description: '[{{ $labels.exporter }}] {{ $labels.instance }} Flask app has two many request counts'
      summary: '{{ $labels.instance }} I might Explode.'
